export { default as logo } from '../assets/Logo.svg'
export { default as logoPres } from '../assets/LogoPes.svg'
export { default as logoPres2 } from '../assets/Logo (1).svg'
export { default as image } from '../assets/Rectangle 1270.svg'
export { default as image2 } from '../assets/Rectangle 1270 (1).svg'
export { default as image3 } from '../assets/Rectangle 1270 (2).svg'
export { default as manOnPhone} from '../assets/Group 216.png'
export { default as checkicon} from '../assets/Group 210.svg'
export { default as arrowdownicon} from '../assets/Group 210 (1).svg'
export { default as woman} from '../assets/Group 281.svg'
export { default as leaf} from '../assets/star.svg'
export { default as eyeIcon} from '../assets/star (1).svg'
export { default as sunIcon} from '../assets/sun.svg'
export { default as user1} from '../assets/Ellipse 4.svg'
export { default as user2} from '../assets/Ellipse 4 (1).svg'
export { default as user3} from '../assets/Ellipse 4 (2).svg'
export { default as team} from '../assets/Rectangle 1270.png'
export { default as image4 } from '../assets/Rectangle 1270 (3).svg'
export { default as image5 } from '../assets/Rectangle 1270 (4).svg'
export { default as image6 } from '../assets/Rectangle 1270 (5).svg'
export { default as darkbg } from '../assets/Mask Group.png'