name: SimplePipeline

on:
  push:
    branches: [main]

jobs:
  securityCheck: 
    name: Security checks
    runs-on: ubuntu-latest
    steps: 
      - name: check for security
        run: |
          echo "Running Security Checks..."
          sleep 5s;
          echo "Running Security Checks... 1"
          sleep 5s;
          echo "Running Security Checks... 2"
          sleep 5s;
          echo "Running Security Checks... 3"
          sleep 5s;

  deploy:
    name: deploying and adding to s3 bucket
    runs-on: ubuntu-latest
    needs: [securityCheck]
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: node upload.cjs

