name: SimplePipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploying and adding to s3 bucket
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - Build: Next.js app
        run: npm run build
